name: CI test

on:
 pull_request:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run test
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy
